#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [[ "$branch" = "master" || "$branch" = "develop" ]]; then
  echo "You can't commit directly to this branch"
  exit 1
fi

npx lint-staged
